cloudposse/terraform-aws-alb

outputs.tf
Remove brackets for listener_arns
was failing on anything larger than 1 with
```
index 1 out of range for list var.listener_arns (max 1) in:
${var.listener_arns[1]}
```
https://github.com/hashicorp/terraform/issues/14521#issuecomment-303492203
=> Remove the brackets `listener_arns` to correct count

README.md, docs/terraform.md, main.tf, variables.tf
This is to enable the option to specify the default target group port in the cases that the service does not listen on port 80.
=> Adding default target group port to accomodate for a TG with a port other than 80

README.md, docs/terraform.md, main.tf, variables.tf
The SSL policy is outdated and consumers may choose to use different values.
@aknysh @osterman
=> Added var for SSL policy changes

README.md, docs/terraform.md, main.tf, variables.tf
This adds 3 new variables (with original defaults to maintain backwards compatibility with older module versions) to the default target group.
1. `target_group_name` - while the default naming scheme enforced by the null-label is nice, I have found valid use cases for specifying a more descriptive custom name for the default target group (while still preserving the naming scheme for the actual ALB).
2. `target_group_target_type` - AWS has three options for target group types, this allows for specifying an option other than the hardcoded `ip`.
3. `target_group_tags` - before this change, the default target group did not have its tags set by the module. This updates it to either optionally pass in your own set of tags (something that I think is useful, just like being able to specify your …
=> Allow customizing the default target group name, target type, and tags

README.md, docs/terraform.md, main.tf, variables.tf
* Allow module consumers to enable log bucket lifecycle
* Enable fine-grained control of retention/tiering
* Use defaults to maintain current behavior for those who don't opt-in
* terraform-aws-s3-log-storage already created lifecycle rule, but control was not bubbled up
* Supports work in terraform-aws-lb-s3-bucket to expose lifecycle settings
* Lifecycle is a standard way to manage s3 assets
* Many will have different requirements, so this provides required flexibility
* Use `closes #39`
=> expose log bucket lifecycle settings

README.md, docs/targets.md, docs/terraform.md, versions.tf
1. Update Version Pinning for Terraform to support 0.13
1. This is a relatively minor update that the CloudPosse module already likely supports.
1. This allows module consumers to not individually update our Terraform module to support Terraform 0.13.
=> [AUTOMATED] Update Version Pinning for Terraform to support 0.13

main.tf
* change version of terraform-aws-lb-s3-bucket module
* version 0.4.0 doesn't work with terraform 0.13.0
=> bump aws-lb-s3-bucket version

main.tf
* module `access_logs` is using tagged version that has issues with TF 0.13, so updating to use a fixed version of that module
* this module currently fails with TF 0.13, and has no tests for TF 0.13 to automatically detect these issues
=> fix: update upsteam dependency

README.md, docs/terraform.md, versions.tf
The `aws = ~> 2.0` causes error in Terraform 0.13:
```
Error: Failed to query available provider packages
Could not retrieve the list of available versions for provider hashicorp/aws:
no available releases match the given constraints >= 3.0.*, >= 2.0.*, >=
2.0.*, >= 2.0.*, >= 2.0.*, >= 2.0.*, < 4.0.*, ~> 2.0, ~> 2.0, ~> 2.0, ~> 2.0,
~> 2.0, ~> 2.0, >= 2.0.*, < 4.0.*, >= 3.0.*, >= 2.0.*, >= 2.0.*, >= 2.0.*
```
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.
* Link to any …
=> Updated version constraints

README.md, docs/terraform.md, main.tf, outputs.tf, variables.tf
This allows the ALB to be created selectively.
As a cost saving measure, I want to be able to create an ALB per AWS account for a given application and then create multiple target groups.  
* This addresses https://github.com/cloudposse/terraform-aws-alb/issues/55.
=> Add enabled variable

.github/workflows/auto-release.yml, README.md, README.yaml, context.tf, docs/terraform.md, examples/complete/context.tf, examples/complete/fixtures.us-east-2.tfvars, examples/complete/main.tf, examples/complete/variables.tf, main.tf, variables.tf
* Bump the tag for s3 bucket module to use `>= 2.0` for aws provider to avoid module version conflicts when used with >= 3.0 modules (eg. aws-eks-node-group).
* Bump the tag to `0.21.0` for `terraform-null-label` module to support future versions of TF.
* This module is being used with [terraform-aws-eks-node-group](https://github.com/cloudposse/terraform-aws-eks-node-group) which needs aws provider version to be >= 2.0 to fix version conflicts.
* See cloudposse/terraform-aws-eks-node-group#41 for details. This tackles one of the modules causing the issue.
=> fix: update s3 bucket & context tags

README.md, docs/terraform.md, main.tf, variables.tf
* Allows the specification of a health check port that is not the traffic-port.
* The health check endpoint doesn't necessarily always exist on the default traffic-port, as is my case.
=> Add health_check_path to allow the health check to use a port other than traffic-port

README.md, docs/terraform.md, variables.tf
* Enable SNI support for https listener when https listener is enabled
* many times an alb is reuse for multiple urls and with SNI support we can attach multiple certs to the same listener
* https://aws.amazon.com/blogs/aws/new-application-load-balancer-sni/
=> Adding SNI cert support

README.md, docs/terraform.md, main.tf, variables.tf
* Add an optional fixed response to the default auction of the listener (http or https).
* I have a case where I am using a Cloudfront distribution that passes a special header to verify the validity of the request (as described here https://www.arhs-group.com/protecting-aws-alb-behind-aws-cloudfront-distribution/). I want to use a listener rule to respond with a 403 if that header is missing or incorrect. Since the module always forwards to the TG unconditionally, I am adding this feature as an alternative.
=> Add fixed response option on listeners (http or https)

README.md, docs/terraform.md, main.tf, variables.tf, versions.tf
This change adds support for the `drop_invalid_header_fields` variable, which was added to the AWS provider, in version `2.54.0` [0].
* Currently, it is not possible to set up this option, which is recommended by the AWS Foundational Security Best Practices controls [1].
* However, it does require the `aws` provider to be at least v2.54.0. If there's any way to maintain the current constraint, and only apply this variable when the version supports it, I'm happy to change the current approach.
* [0] https://github.com/hashicorp/terraform-provider-aws/commit/956f2e68e2455a8474296b08ee559d6aaeca48ea
* [1] https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-standards-fsbp-controls.html#fsbp-elb-4
=> Add drop_invalid_header_fields variable

main.tf
* Describe high-level what changed as a result of these commits (i.e. in plain-english, what do these changes mean?)
* Use bullet points to be concise and to the point.
- Context, as inherited from the user defined context, is passed and used in the access_logs
* Provide the justifications for the changes (e.g. business case). 
* Describe why these changes were made (e.g. why do these commits fix the problem?)
* Use bullet points to be concise and to the point.
- Bug found where the s3 bucket was not using our defined context label_order `label_order              = ["namespace", "environment", "name", "attributes"]`.  The bucket being created was still using our defined stage of prod.  In our use case, if the context is passed in, label_order will be respected by the lb-s3-bucket.
- This …
=> Pass module.this.context to cloudposse/lb-s3-bucket/aws

README.md, docs/terraform.md, examples/complete/versions.tf, versions.tf
* remove unused template provider
* broken on darwin-arm64
```
│ Error: Incompatible provider version
│ 
│ Provider registry.terraform.io/hashicorp/template v2.2.0 does not have a
│ package available for your current platform, darwin_arm64.
│ 
│ Provider releases are separate from Terraform CLI releases, so not all
│ providers are available for all platforms. Other versions of this provider
│ may have different platforms supported.
```
=> Remove unused template provider

README.md, docs/terraform.md, main.tf, variables.tf
* Ensure target group and load balancer names cannot exceed their max length
* Expose `*_max_length` variables in case AWS changes their max length in the future
* Override `load_balancer_name`, similar to `target_group_name`
* To prevent exceeding the max lengths of the tg and lb so the module will be applied correctly
* Closes https://github.com/cloudposse/terraform-aws-alb/issues/27
* [API_CreateTargetGroup](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateTargetGroup.html)
> This name must be unique per region per account, can have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, and must not begin or end with a hyphen.
* [API_CreateLoadBalancer](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_Creat …
=> Ensure target group and load balancer names cannot exceed their max length

main.tf
* Add `module.this.enabled` check to listener's `count`
* To ensure this module can be properly disabled using `enabled = false`
* Closes https://github.com/cloudposse/terraform-aws-alb/issues/90
* Closes https://github.com/cloudposse/terraform-aws-alb/issues/94
=> Add `module.this.enabled` check to listener's `count`

README.md, docs/terraform.md, main.tf, variables.tf
Add variable to support health check protocol different from traffic's
My system uses HTTP for the health check but HTTPS for data traffic.   
Add a new variable to support this use case.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group#health_check
=> feat: add variable to support health check protocol different from traffic's

.github/renovate.json, README.md, docs/terraform.md, main.tf, variables.tf, versions.tf
* Add attribute `protocol_version` to default target group
* This attribute is mentioned in docs for lb_target_group https://registry.terraform.io/providers/hashicorp/aws/3.61.0/docs/resources/lb_target_group#protocol_version
=> Add attribute protocol_version into default target group

docs/terraform.md, main.tf
Fixes #134 - Does not create http_forward when aws_lb_target_group.default is disabled
* disables aws_lb_listener.http_forward when default_target_group is not enabled
* target_group is required when type is 'redirect'
See #134.  Fixes this Validation error when default_target_group_enabled == 0 :
```
module.alb.aws_lb_listener.http_forward[0]: Creating...
╷
│ Error: creating ELBv2 Listener
(arn:aws:elasticloadbalancing:...:...:loadbalancer/...):
ValidationError: A target group ARN must be specified
│       status code: 400, request id:
7cf9d727-fc77-4d32-a160-deadbeefcafe
│
│   with module.alb.aws_lb_listener.http_forward[0],
│   on .terraform/modules/alb/main.tf line 150, in resource
"aws_lb_listener" "http_forward":
│  150: resource "aws_lb_listener" "http_forward" {
```
closes #134
=> Fixes #134 - Does not create http_forward when aws_lb_target_group.default is disabled

README.md, docs/terraform.md, main.tf, variables.tf
Adds `http_ingress_security_group_ids` and `https_ingress_security_group_ids` and clarifies that `security_group_ids` does not allow access to the ALB from the security groups passed in.
Behaviour was misleading.
Resolves https://github.com/cloudposse/terraform-aws-alb/issues/197
=> allow alb ingress from security groups
